__author__ = 'zhongyaqi'
username='noxus7'
password='noxus1205'
app='com.wuba'
udid='2bae31c8'
platform='Android'
port='4723'
test_report_root='/usr/local/opt/tmmp/data/report/uireport/Android/'
